### PR TITLE
fix: partial playready drm support

### LINKED ISSUE #142: PlayReady DRM
Microsoft also made some contribution into HLS format, to support their PlayReady DRM.

See
https://docs.microsoft.com/en-us/playready/packaging/mp4-based-formats-supported-by-playready-clients?tabs=case4

I don't have alive HLS stream with PlayReady to check, and actually I am not sure, how to test playback here, because with the death of old Edge there are no more browsers with PlayReady support on the desktop platform, as far as I know.

But I think minimal change need to be done to avoid issue like #139, filter out `EXT-X-KEY` rows with `KEYFORMAT="com.microsoft.playready"`

### PR DESCRIPTION
**Pull request by brandonocasey**
Fixes #142

### CODE REVIEW

File: src/parser.js [hunk 1]
```diff
@@ -263,6 +263,17 @@ export default class Parser extends Stream {
                 return;
               }
 
+              if (entry.attributes.KEYFORMAT === 'com.microsoft.playready') {
+                this.manifest.contentProtection = this.manifest.contentProtection || {};
+
+                // TODO: add full support for this.
+                this.manifest.contentProtection['com.microsoft.playready'] = {
+                  url: entry.attributes.URI
```
Comment (gesinger) [inline src/parser.js:271]: Since the attribute is `URI` and we use `uri` in most places within the parser, it may make sense to use `uri` here.

Comment (brandonocasey) [reply src/parser.js:271]: seems like we use `url` for `keySystems`

Comment (gesinger) [reply src/parser.js:271]: Yeah, I think that was my mistake when using both `uri` and `url` within videojs-contrib-eme's options. I wonder if we're better off for parsing within m3u8-parser trying to keep consistent with the naming, and then do translation if we have to in VHS. It might also make sense to rename the `url` option in videojs-contrib-eme to `uri`, or at least make both available.

**Review by gesinger — APPROVED** [review]
